// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// NewCreateGrantTypeJwtBearerParams creates a new CreateGrantTypeJwtBearerParams object
// with the default values initialized.
func NewCreateGrantTypeJwtBearerParams() *CreateGrantTypeJwtBearerParams {
	var ()
	return &CreateGrantTypeJwtBearerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGrantTypeJwtBearerParamsWithTimeout creates a new CreateGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGrantTypeJwtBearerParamsWithTimeout(timeout time.Duration) *CreateGrantTypeJwtBearerParams {
	var ()
	return &CreateGrantTypeJwtBearerParams{

		timeout: timeout,
	}
}

// NewCreateGrantTypeJwtBearerParamsWithContext creates a new CreateGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateGrantTypeJwtBearerParamsWithContext(ctx context.Context) *CreateGrantTypeJwtBearerParams {
	var ()
	return &CreateGrantTypeJwtBearerParams{

		Context: ctx,
	}
}

// NewCreateGrantTypeJwtBearerParamsWithHTTPClient creates a new CreateGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateGrantTypeJwtBearerParamsWithHTTPClient(client *http.Client) *CreateGrantTypeJwtBearerParams {
	var ()
	return &CreateGrantTypeJwtBearerParams{
		HTTPClient: client,
	}
}

/*CreateGrantTypeJwtBearerParams contains all the parameters to send to the API endpoint
for the create grant type jwt bearer operation typically these are written to a http.Request
*/
type CreateGrantTypeJwtBearerParams struct {

	/*Body
	  Request Body

	*/
	Body *models.CreateGrantTypeJwtBearerParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) WithTimeout(timeout time.Duration) *CreateGrantTypeJwtBearerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) WithContext(ctx context.Context) *CreateGrantTypeJwtBearerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) WithHTTPClient(client *http.Client) *CreateGrantTypeJwtBearerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) WithBody(body *models.CreateGrantTypeJwtBearerParams) *CreateGrantTypeJwtBearerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create grant type jwt bearer params
func (o *CreateGrantTypeJwtBearerParams) SetBody(body *models.CreateGrantTypeJwtBearerParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGrantTypeJwtBearerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
