// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// DeleteGrantTypeJwtBearerReader is a Reader for the DeleteGrantTypeJwtBearer structure.
type DeleteGrantTypeJwtBearerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGrantTypeJwtBearerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteGrantTypeJwtBearerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteGrantTypeJwtBearerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteGrantTypeJwtBearerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGrantTypeJwtBearerNoContent creates a DeleteGrantTypeJwtBearerNoContent with default headers values
func NewDeleteGrantTypeJwtBearerNoContent() *DeleteGrantTypeJwtBearerNoContent {
	return &DeleteGrantTypeJwtBearerNoContent{}
}

/*DeleteGrantTypeJwtBearerNoContent handles this case with default header values.

Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is
typically 201.
*/
type DeleteGrantTypeJwtBearerNoContent struct {
}

func (o *DeleteGrantTypeJwtBearerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /grants/jwt-bearer/{id}][%d] deleteGrantTypeJwtBearerNoContent ", 204)
}

func (o *DeleteGrantTypeJwtBearerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGrantTypeJwtBearerNotFound creates a DeleteGrantTypeJwtBearerNotFound with default headers values
func NewDeleteGrantTypeJwtBearerNotFound() *DeleteGrantTypeJwtBearerNotFound {
	return &DeleteGrantTypeJwtBearerNotFound{}
}

/*DeleteGrantTypeJwtBearerNotFound handles this case with default header values.

genericError
*/
type DeleteGrantTypeJwtBearerNotFound struct {
	Payload *models.GenericError
}

func (o *DeleteGrantTypeJwtBearerNotFound) Error() string {
	return fmt.Sprintf("[DELETE /grants/jwt-bearer/{id}][%d] deleteGrantTypeJwtBearerNotFound  %+v", 404, o.Payload)
}

func (o *DeleteGrantTypeJwtBearerNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteGrantTypeJwtBearerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteGrantTypeJwtBearerInternalServerError creates a DeleteGrantTypeJwtBearerInternalServerError with default headers values
func NewDeleteGrantTypeJwtBearerInternalServerError() *DeleteGrantTypeJwtBearerInternalServerError {
	return &DeleteGrantTypeJwtBearerInternalServerError{}
}

/*DeleteGrantTypeJwtBearerInternalServerError handles this case with default header values.

genericError
*/
type DeleteGrantTypeJwtBearerInternalServerError struct {
	Payload *models.GenericError
}

func (o *DeleteGrantTypeJwtBearerInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /grants/jwt-bearer/{id}][%d] deleteGrantTypeJwtBearerInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteGrantTypeJwtBearerInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteGrantTypeJwtBearerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
