// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGrantTypeJwtBearerParams creates a new DeleteGrantTypeJwtBearerParams object
// with the default values initialized.
func NewDeleteGrantTypeJwtBearerParams() *DeleteGrantTypeJwtBearerParams {
	var ()
	return &DeleteGrantTypeJwtBearerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGrantTypeJwtBearerParamsWithTimeout creates a new DeleteGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteGrantTypeJwtBearerParamsWithTimeout(timeout time.Duration) *DeleteGrantTypeJwtBearerParams {
	var ()
	return &DeleteGrantTypeJwtBearerParams{

		timeout: timeout,
	}
}

// NewDeleteGrantTypeJwtBearerParamsWithContext creates a new DeleteGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteGrantTypeJwtBearerParamsWithContext(ctx context.Context) *DeleteGrantTypeJwtBearerParams {
	var ()
	return &DeleteGrantTypeJwtBearerParams{

		Context: ctx,
	}
}

// NewDeleteGrantTypeJwtBearerParamsWithHTTPClient creates a new DeleteGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteGrantTypeJwtBearerParamsWithHTTPClient(client *http.Client) *DeleteGrantTypeJwtBearerParams {
	var ()
	return &DeleteGrantTypeJwtBearerParams{
		HTTPClient: client,
	}
}

/*DeleteGrantTypeJwtBearerParams contains all the parameters to send to the API endpoint
for the delete grant type jwt bearer operation typically these are written to a http.Request
*/
type DeleteGrantTypeJwtBearerParams struct {

	/*ID
	  The id of the desired grant

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) WithTimeout(timeout time.Duration) *DeleteGrantTypeJwtBearerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) WithContext(ctx context.Context) *DeleteGrantTypeJwtBearerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) WithHTTPClient(client *http.Client) *DeleteGrantTypeJwtBearerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) WithID(id string) *DeleteGrantTypeJwtBearerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete grant type jwt bearer params
func (o *DeleteGrantTypeJwtBearerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGrantTypeJwtBearerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
