// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGrantTypeJwtBearerParams creates a new GetGrantTypeJwtBearerParams object
// with the default values initialized.
func NewGetGrantTypeJwtBearerParams() *GetGrantTypeJwtBearerParams {
	var ()
	return &GetGrantTypeJwtBearerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGrantTypeJwtBearerParamsWithTimeout creates a new GetGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGrantTypeJwtBearerParamsWithTimeout(timeout time.Duration) *GetGrantTypeJwtBearerParams {
	var ()
	return &GetGrantTypeJwtBearerParams{

		timeout: timeout,
	}
}

// NewGetGrantTypeJwtBearerParamsWithContext creates a new GetGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGrantTypeJwtBearerParamsWithContext(ctx context.Context) *GetGrantTypeJwtBearerParams {
	var ()
	return &GetGrantTypeJwtBearerParams{

		Context: ctx,
	}
}

// NewGetGrantTypeJwtBearerParamsWithHTTPClient creates a new GetGrantTypeJwtBearerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGrantTypeJwtBearerParamsWithHTTPClient(client *http.Client) *GetGrantTypeJwtBearerParams {
	var ()
	return &GetGrantTypeJwtBearerParams{
		HTTPClient: client,
	}
}

/*GetGrantTypeJwtBearerParams contains all the parameters to send to the API endpoint
for the get grant type jwt bearer operation typically these are written to a http.Request
*/
type GetGrantTypeJwtBearerParams struct {

	/*ID
	  The id of the desired grant

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) WithTimeout(timeout time.Duration) *GetGrantTypeJwtBearerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) WithContext(ctx context.Context) *GetGrantTypeJwtBearerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) WithHTTPClient(client *http.Client) *GetGrantTypeJwtBearerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) WithID(id string) *GetGrantTypeJwtBearerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get grant type jwt bearer params
func (o *GetGrantTypeJwtBearerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetGrantTypeJwtBearerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
