// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// GetGrantTypeJwtBearerListReader is a Reader for the GetGrantTypeJwtBearerList structure.
type GetGrantTypeJwtBearerListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGrantTypeJwtBearerListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGrantTypeJwtBearerListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetGrantTypeJwtBearerListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGrantTypeJwtBearerListOK creates a GetGrantTypeJwtBearerListOK with default headers values
func NewGetGrantTypeJwtBearerListOK() *GetGrantTypeJwtBearerListOK {
	return &GetGrantTypeJwtBearerListOK{}
}

/*GetGrantTypeJwtBearerListOK handles this case with default header values.

List of Grant Types for JWT Bearer Profile
*/
type GetGrantTypeJwtBearerListOK struct {
	Payload []*models.GrantTypeJwtBearer
}

func (o *GetGrantTypeJwtBearerListOK) Error() string {
	return fmt.Sprintf("[GET /grants/jwt-bearer][%d] getGrantTypeJwtBearerListOK  %+v", 200, o.Payload)
}

func (o *GetGrantTypeJwtBearerListOK) GetPayload() []*models.GrantTypeJwtBearer {
	return o.Payload
}

func (o *GetGrantTypeJwtBearerListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGrantTypeJwtBearerListInternalServerError creates a GetGrantTypeJwtBearerListInternalServerError with default headers values
func NewGetGrantTypeJwtBearerListInternalServerError() *GetGrantTypeJwtBearerListInternalServerError {
	return &GetGrantTypeJwtBearerListInternalServerError{}
}

/*GetGrantTypeJwtBearerListInternalServerError handles this case with default header values.

genericError
*/
type GetGrantTypeJwtBearerListInternalServerError struct {
	Payload *models.GenericError
}

func (o *GetGrantTypeJwtBearerListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /grants/jwt-bearer][%d] getGrantTypeJwtBearerListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGrantTypeJwtBearerListInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetGrantTypeJwtBearerListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
