// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGrantTypeJwtBearerListParams creates a new GetGrantTypeJwtBearerListParams object
// with the default values initialized.
func NewGetGrantTypeJwtBearerListParams() *GetGrantTypeJwtBearerListParams {
	var ()
	return &GetGrantTypeJwtBearerListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGrantTypeJwtBearerListParamsWithTimeout creates a new GetGrantTypeJwtBearerListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGrantTypeJwtBearerListParamsWithTimeout(timeout time.Duration) *GetGrantTypeJwtBearerListParams {
	var ()
	return &GetGrantTypeJwtBearerListParams{

		timeout: timeout,
	}
}

// NewGetGrantTypeJwtBearerListParamsWithContext creates a new GetGrantTypeJwtBearerListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGrantTypeJwtBearerListParamsWithContext(ctx context.Context) *GetGrantTypeJwtBearerListParams {
	var ()
	return &GetGrantTypeJwtBearerListParams{

		Context: ctx,
	}
}

// NewGetGrantTypeJwtBearerListParamsWithHTTPClient creates a new GetGrantTypeJwtBearerListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGrantTypeJwtBearerListParamsWithHTTPClient(client *http.Client) *GetGrantTypeJwtBearerListParams {
	var ()
	return &GetGrantTypeJwtBearerListParams{
		HTTPClient: client,
	}
}

/*GetGrantTypeJwtBearerListParams contains all the parameters to send to the API endpoint
for the get grant type jwt bearer list operation typically these are written to a http.Request
*/
type GetGrantTypeJwtBearerListParams struct {

	/*Issuer
	  If Optional "issuer" is supplied, only jwt-bearer grants with this issuer will be returned.

	*/
	Issuer *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) WithTimeout(timeout time.Duration) *GetGrantTypeJwtBearerListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) WithContext(ctx context.Context) *GetGrantTypeJwtBearerListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) WithHTTPClient(client *http.Client) *GetGrantTypeJwtBearerListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIssuer adds the issuer to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) WithIssuer(issuer *string) *GetGrantTypeJwtBearerListParams {
	o.SetIssuer(issuer)
	return o
}

// SetIssuer adds the issuer to the get grant type jwt bearer list params
func (o *GetGrantTypeJwtBearerListParams) SetIssuer(issuer *string) {
	o.Issuer = issuer
}

// WriteToRequest writes these params to a swagger request
func (o *GetGrantTypeJwtBearerListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Issuer != nil {

		// query param issuer
		var qrIssuer string
		if o.Issuer != nil {
			qrIssuer = *o.Issuer
		}
		qIssuer := qrIssuer
		if qIssuer != "" {
			if err := r.SetQueryParam("issuer", qIssuer); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
