// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// GetGrantTypeJwtBearerReader is a Reader for the GetGrantTypeJwtBearer structure.
type GetGrantTypeJwtBearerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGrantTypeJwtBearerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGrantTypeJwtBearerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetGrantTypeJwtBearerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGrantTypeJwtBearerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGrantTypeJwtBearerOK creates a GetGrantTypeJwtBearerOK with default headers values
func NewGetGrantTypeJwtBearerOK() *GetGrantTypeJwtBearerOK {
	return &GetGrantTypeJwtBearerOK{}
}

/*GetGrantTypeJwtBearerOK handles this case with default header values.

grantTypeJwtBearer
*/
type GetGrantTypeJwtBearerOK struct {
	Payload *models.GrantTypeJwtBearer
}

func (o *GetGrantTypeJwtBearerOK) Error() string {
	return fmt.Sprintf("[GET /grants/jwt-bearer/{id}][%d] getGrantTypeJwtBearerOK  %+v", 200, o.Payload)
}

func (o *GetGrantTypeJwtBearerOK) GetPayload() *models.GrantTypeJwtBearer {
	return o.Payload
}

func (o *GetGrantTypeJwtBearerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrantTypeJwtBearer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGrantTypeJwtBearerNotFound creates a GetGrantTypeJwtBearerNotFound with default headers values
func NewGetGrantTypeJwtBearerNotFound() *GetGrantTypeJwtBearerNotFound {
	return &GetGrantTypeJwtBearerNotFound{}
}

/*GetGrantTypeJwtBearerNotFound handles this case with default header values.

genericError
*/
type GetGrantTypeJwtBearerNotFound struct {
	Payload *models.GenericError
}

func (o *GetGrantTypeJwtBearerNotFound) Error() string {
	return fmt.Sprintf("[GET /grants/jwt-bearer/{id}][%d] getGrantTypeJwtBearerNotFound  %+v", 404, o.Payload)
}

func (o *GetGrantTypeJwtBearerNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetGrantTypeJwtBearerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGrantTypeJwtBearerInternalServerError creates a GetGrantTypeJwtBearerInternalServerError with default headers values
func NewGetGrantTypeJwtBearerInternalServerError() *GetGrantTypeJwtBearerInternalServerError {
	return &GetGrantTypeJwtBearerInternalServerError{}
}

/*GetGrantTypeJwtBearerInternalServerError handles this case with default header values.

genericError
*/
type GetGrantTypeJwtBearerInternalServerError struct {
	Payload *models.GenericError
}

func (o *GetGrantTypeJwtBearerInternalServerError) Error() string {
	return fmt.Sprintf("[GET /grants/jwt-bearer/{id}][%d] getGrantTypeJwtBearerInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGrantTypeJwtBearerInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetGrantTypeJwtBearerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
